### ISSUE TITLE
SublimeLinter-html-tidy make the paths configuration not work

### ISSUE THREAD

**Issue by ian4hu** [SublimeLinter/SublimeLinter-html-tidy#33]
I have SublimeLinter-html-tidy, SublimeLinter-php, SublimeLinter-phpcs installed before, and configured the "paths" (by add additional directory, I didn't add tidy.exe php.exe's fold to my PATH environment variable) to make them work fine. but all of them stopped work after a recent update. I'm not sure which update make it. so I remove package one by one to try to make it work, and finally found  after SublimeLinter-html-tidy removed, the other linter worked again.

And I found with SublimeLinter-html-tidy installed, the method https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/util.py#L713 execute before https://github.com/SublimeLinter/SublimeLinter3/blob/master/sublimelinter.py#L28 (by view the debug log of SublimeLinter) and make the "paths" not loaded.

**Comment by skj3gg** [comment]
Sorry you're having issues,

What does your entire debug console look like after startup?

**Comment by hu2008yinxiang** [comment]
Here are several entire debug log (all with SublimeLinter's debug:true):
1. without SublimeLinter-html-tidy and worked fine.

```php
DPI scale: 1
startup, version: 3083 windows x32 channel: stable
executable: /D/Program Files (x86)/Sublime Text/sublime_text.exe
working dir: /D/Program Files (x86)/Sublime Text
packages path: /D/Program Files (x86)/Sublime Text/Data/Packages
state path: /D/Program Files (x86)/Sublime Text/Data/Local
zip path: /D/Program Files (x86)/Sublime Text/Packages
zip path: /D/Program Files (x86)/Sublime Text/Data/Installed Packages
ignored_packages: ["Vintage", "Markdown"]
pre session restore time: 0.222841
startup time: 0.268841
first paint time: 0.284841
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin AutoPEP8.sublautopep8
reloading plugin Better Completion.main
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin Clipboard Manager.clipboard_manager
reloading plugin Codec.codec_base64
reloading plugin Codec.codec_json
reloading plugin Codec.codec_quopri
reloading plugin Codec.codec_xml
reloading plugin Codec.sublime_codec
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorPicker.sublimecp
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin JsFormat.js_formatter
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
[WinError 2] 系统找不到指定的文件。
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeEnhancedUtilitiesSet.commands
Some dependencies has not been imported for Utilities package; some utilities functionality will not be availiable
reloading plugin SublimeEnhancedUtilitiesSet.go
Traceback (most recent call last):
  File "D:\Program Files (x86)\Sublime Text\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Program Files (x86)\Sublime Text\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "go in D:\Program Files (x86)\Sublime Text\Data\Installed Packages\SublimeEnhancedUtilitiesSet.sublime-package", line 2, in <module>
ImportError: No module named 'Expression'
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SublimeLinter-phplint.linter
SublimeLinter: phplint linter loaded 
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin Toggle Read-Only.toggle_readonly
reloading plugin Toggle the View Read-Only.toggle_readonly
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin IMESupport.imesupportplugin
reloading plugin SFTP.SFTP
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-phpcs.linter
SublimeLinter: phpcs linter loaded 
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin SVN.SVN
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\xuanyuan\appdata\local\temp\SublimeLinter3-XuanYuan 
SublimeLinter: computed PATH from system:
D:\Program Files (x86)\phplint\
D:\Program Files (x86)\PHP\
D:\Program Files (x86)\
D:\Program Files (x86)\PHP_CodeSniffer\scripts\
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
C:\Program Files\TortoiseSVN\bin
D:\Program Files (x86)\VanDyke Software\Clients\
D:\Program Files\nodejs\
D:\Program Files\nodejs\npm-global\
D:\Program Files (x86)\Java\jdk1.8.0_45\bin
C:\HashiCorp\Vagrant\bin

 
SublimeLinter: php activated: D:\Program Files (x86)\PHP\php.exe 
SublimeLinter: phpcs activated: D:\Program Files (x86)\PHP_CodeSniffer\scripts\phpcs.bat 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: phplint version query: D:\Program Files (x86)\phplint\phplint.bat --version 
SublimeLinter: phplint version: 2.1 
SublimeLinter: phplint: (>= 1.1) satisfied by 2.1 
SublimeLinter: phplint activated: D:\Program Files (x86)\phplint\phplint.bat 
Emmet: No need to update PyV8
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
SublimeLinter: phpcs: index.php ['D:\\Program Files (x86)\\PHP_CodeSniffer\\scripts\\phpcs.bat', '--report=checkstyle', '--tab-width=4', '--extensions=php', '--standard=PSR1', '--standard=PSR2'] 
SublimeLinter: phpcs output:
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.1.0">
<file name="C:\Users\XuanYuan\AppData\Local\Temp\SublimeLinter3-XuanYuan\index.php">
 <error line="2" column="10" severity="error" message="Expected 1 newline at end of file; 0 found" source="PSR2.Files.EndFileNewline.NoneFound"/>
</file>
</checkstyle> 
SublimeLinter: phplint: index.php ['D:\\Program Files (x86)\\phplint\\phplint.bat', '--print-path', 'shortest', '--print-context', '--tab-size', '4', '--no-overall'] 

SublimeLinter: phplint output:
BEGIN parsing of ../appdata/local/temp/SublimeLinter3-XuanYuan/index.php
1:  <?php
2:  E_ALL = 1;

    E_ALL = 1;
           \_ HERE
==== 2: ERROR: unknown constant E_ALL

    E_ALL = 1;
           \_ HERE
==== 2: ERROR: missing statement terminator `;' or `?>'

    E_ALL = 1;
           \_ HERE
==== 2: ERROR: (FATAL) unexpected symbol sym_assign 
SublimeLinter: php: index.php ['D:\\Program Files (x86)\\PHP\\php.exe', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off'] 
SublimeLinter: php output:

Parse error: syntax error, unexpected '=' in - on line 2
Errors parsing - 

```

**Comment by hu2008yinxiang** [comment]
2. then I installed SublimeLinter-html-tidy (also work but all of them stopped working after restart sublime):

```php
DPI scale: 1
startup, version: 3083 windows x32 channel: stable
executable: /D/Program Files (x86)/Sublime Text/sublime_text.exe
working dir: /C/Users/XuanYuan/Desktop
packages path: /D/Program Files (x86)/Sublime Text/Data/Packages
state path: /D/Program Files (x86)/Sublime Text/Data/Local
zip path: /D/Program Files (x86)/Sublime Text/Packages
zip path: /D/Program Files (x86)/Sublime Text/Data/Installed Packages
ignored_packages: ["Markdown", "Vintage"]
pre session restore time: 0.247469
startup time: 0.294469
first paint time: 0.310468
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin AutoPEP8.sublautopep8
reloading plugin Better Completion.main
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin Clipboard Manager.clipboard_manager
reloading plugin Codec.codec_base64
reloading plugin Codec.codec_json
reloading plugin Codec.codec_quopri
reloading plugin Codec.codec_xml
reloading plugin Codec.sublime_codec
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorPicker.sublimecp
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin JsFormat.js_formatter
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
[WinError 2] 系统找不到指定的文件。
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeEnhancedUtilitiesSet.commands
Some dependencies has not been imported for Utilities package; some utilities functionality will not be availiable
reloading plugin SublimeEnhancedUtilitiesSet.go
Traceback (most recent call last):
  File "D:\Program Files (x86)\Sublime Text\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Program Files (x86)\Sublime Text\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "go in D:\Program Files (x86)\Sublime Text\Data\Installed Packages\SublimeEnhancedUtilitiesSet.sublime-package", line 2, in <module>
ImportError: No module named 'Expression'
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SublimeLinter-phplint.linter
SublimeLinter: phplint linter loaded 
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin Toggle Read-Only.toggle_readonly
reloading plugin Toggle the View Read-Only.toggle_readonly
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin IMESupport.imesupportplugin
reloading plugin SFTP.SFTP
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-phpcs.linter
SublimeLinter: phpcs linter loaded 
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin SVN.SVN
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\xuanyuan\appdata\local\temp\SublimeLinter3-XuanYuan 
SublimeLinter: WARNING: phpcs deactivated, cannot locate 'phpcs' 
SublimeLinter: WARNING: htmltidy deactivated, cannot locate 'tidy' 
SublimeLinter: WARNING: phplint deactivated, cannot locate 'phplint' 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: WARNING: php deactivated, cannot locate 'php' 
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
SublimeLinter: annotations activated: <builtin> 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-06-18 09:09:16, next run at 2015-06-18 10:09:16 or after

```

**Comment by hu2008yinxiang** [comment]
3. then I change the code https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/util.py#L745 here to 

```python
 if persist.debug_mode() or True:
```

the log changed to:

```php
DPI scale: 1
startup, version: 3083 windows x32 channel: stable
executable: /D/Program Files (x86)/Sublime Text/sublime_text.exe
working dir: /D/Program Files (x86)/Sublime Text
packages path: /D/Program Files (x86)/Sublime Text/Data/Packages
state path: /D/Program Files (x86)/Sublime Text/Data/Local
zip path: /D/Program Files (x86)/Sublime Text/Packages
zip path: /D/Program Files (x86)/Sublime Text/Data/Installed Packages
ignored_packages: ["Markdown", "Vintage"]
pre session restore time: 0.246952
startup time: 0.294953
first paint time: 0.306953
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin AutoPEP8.sublautopep8
reloading plugin Better Completion.main
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin Clipboard Manager.clipboard_manager
reloading plugin Codec.codec_base64
reloading plugin Codec.codec_json
reloading plugin Codec.codec_quopri
reloading plugin Codec.codec_xml
reloading plugin Codec.sublime_codec
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorPicker.sublimecp
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin JsFormat.js_formatter
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
[WinError 2] 系统找不到指定的文件。
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeEnhancedUtilitiesSet.commands
Some dependencies has not been imported for Utilities package; some utilities functionality will not be availiable
reloading plugin SublimeEnhancedUtilitiesSet.go
Traceback (most recent call last):
  File "D:\Program Files (x86)\Sublime Text\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Program Files (x86)\Sublime Text\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "go in D:\Program Files (x86)\Sublime Text\Data\Installed Packages\SublimeEnhancedUtilitiesSet.sublime-package", line 2, in <module>
ImportError: No module named 'Expression'
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: computed PATH from system:
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
C:\Program Files\TortoiseSVN\bin
D:\Program Files (x86)\VanDyke Software\Clients\
D:\Program Files\nodejs\
D:\Program Files\nodejs\npm-global\
D:\Program Files (x86)\Java\jdk1.8.0_45\bin
C:\HashiCorp\Vagrant\bin

 
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SublimeLinter-phplint.linter
SublimeLinter: phplint linter loaded 
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin Toggle Read-Only.toggle_readonly
reloading plugin Toggle the View Read-Only.toggle_readonly
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin IMESupport.imesupportplugin
reloading plugin SFTP.SFTP
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-phpcs.linter
SublimeLinter: phpcs linter loaded 
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin SVN.SVN
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\xuanyuan\appdata\local\temp\SublimeLinter3-XuanYuan 
SublimeLinter: WARNING: phpcs deactivated, cannot locate 'phpcs' 
SublimeLinter: WARNING: phplint deactivated, cannot locate 'phplint' 
SublimeLinter: WARNING: htmltidy deactivated, cannot locate 'tidy' 
SublimeLinter: WARNING: php deactivated, cannot locate 'php' 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-06-18 09:09:16, next run at 2015-06-18 10:09:16 or after

```

**Comment by hu2008yinxiang** [comment]
my Sublime Linter config is:

```javascript
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "annotations": {
                "@disable": false,
                "args": [],
                "errors": [
                    "FIXME"
                ],
                "excludes": [],
                "warnings": [
                    "TODO",
                    "README"
                ]
            },
            "htmltidy": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "php": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phpcs": {
                "@disable": false,
                "args": [
                    "--tab-width=4",
                    "--extensions=php"
                ],
                "excludes": [],
                "standard": [
                    "PSR1",
                    "PSR2"
                ]
            },
            "phplint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "stippled underline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "D:\\Program Files (x86)\\phplint\\",
                "D:\\Program Files (x86)\\PHP\\",
                "D:\\Program Files (x86)\\",
                "D:\\Program Files (x86)\\PHP_CodeSniffer\\scripts\\"
            ]
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by hu2008yinxiang** [comment]
After digged into code I found in https://github.com/SublimeLinter/SublimeLinter-html-tidy/blob/master/linter.py#L21 the ```python  if Linter.which('tidy5'):``` cause the SublimeLinter.lint.util.which(cmd) called before the SublimeLinter.lint.persist.settings.load() https://github.com/SublimeLinter/SublimeLinter3/blob/master/sublimelinter.py#L29 , and in SublimeLinter.lint.util.which(cmd) the SublimeLinter.lint.util.find_executable https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/util.py#L806 was called, in SublimeLinter.lint.util.find_executable the SublimeLinter.lint.util.create_environment was called TOO EARLY AND BE CACHED https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/util.py#L1088

My English is poor, if these make you confused, sorry. may the call stack of SublimeLinter.lint.util.create_environment help.

**Comment by 0xc6** [comment]
Can verify. To expand: having SublimeLinter-html-tidy installed _at all_ causes the problem, toggling said linter off does not fix said problem: one must entirely remove SL-html-tidy from one's system (via packagecontrol) if one wants to have SL utilise paths.

**Comment by hu2008yinxiang** [comment]
Should this be a bug? in SublimeLinter or SL-html-tidy?

**Comment by auz9** [comment]
Hi,
Thank you ian4hu for paving the road.  
> Should this be a bug? in SublimeLinter or SL-html-tidy?

It seems to me that this bug is most likely with SublimeLinter.
If _Linter.which('tidy5')_ is avoided in _SublimeLinter-html-tidy_ > _linter.py_ , all other linters work in harmony. 
```
from SublimeLinter.lint import Linter, util

class HtmlTidy(Linter):

    """Provides an interface to tidy."""

    syntax = 'html'
    cmd = 'tidy -errors -quiet -utf8'


    regex = r'^line (?P<line>\d+) column (?P<col>\d+) - (?:(?P<error>Error)|(?P<warning>Warning)): (?P<message>.+)'
    error_stream = util.STREAM_STDERR
```
 To use _tidy5_, simply create a symbolic link in the file system.
```
root# ln -s /usr/bin/tidy5 /usr/local/bin/tidy
```

Also affected:
SublimeText3 ver 3083 on
ArchLinux x64 kernel lts-4.1.16-1, KDE 5
LinuxMint/Ubuntu x64 kernel 3.13.0-76, KDE 4

**Comment by auz9** [comment]
Sorry for the duplicates..  Please ignore.

**Comment by ExoKalork** [comment]
Is there a fix for windows ?
